import numpy as np

from config import PanelArea, PanelEfficiency, RaceStartTime, RaceEndTime

DT = RaceEndTime - RaceStartTime
_power_coeff = PanelArea * PanelEfficiency

def _calc_solar_irradiance(time):
    return 1073.099 * np.exp(-0.5 * ((time - 51908.735) / 11484.950)**2)

def calculate_incident_solarpower(globaltime, latitude, longitude):
    # Calculate power generated by solar in the path
    gt = globaltime % DT
    intensity = _calc_solar_irradiance(RaceStartTime + gt)
    return intensity * _power_coeff